title: Popular U.S. Baby Names
slug: popular-babynames-via-ssa
description: |
  Popular U.S. baby names based on Social Security card applications.
source:
  publisher: Social Security Administration
  url: https://www.ssa.gov/
