- title: Download and unpack the data files
  description: |
    Download, save, and unpack the two zip files from ssa.gov.
  path: fetching/download-and-unpack.py
  language:
    name: Python
    version: 3.5
    dependencies:
      - requests

  documentation: |
    Downloads and unzips the nationwide and state data files directly from the Social Security Administration's website:

    https://www.ssa.gov/oact/babynames/limits.html

    Two zip files are saved:

    - datasets/babynames/fetched/states.zip
    - datasets/babynames/fetched/nationwide.zip

    The zip files are unpacked into these subdirectories:

    - datasets/babynames/fetched/states/
    - datasets/babynames/fetched/nationwide/
